export const ActionTypes = {
  CREATE_PRODUCT_REQUESTED: 'CREATE_PRODUCT_REQUESTED',
  CREATE_PRODUCT_SUCCESS: 'CREATE_PRODUCT_SUCCESS',
  CREATE_PRODUCT_FAIL: 'CREATE_PRODUCT_FAIL',
  GET_PRODUCTS_REQUESTED: 'GET_PRODUCTS_REQUESTED',
  GET_PRODUCTS_SUCCESS: 'GET_PRODUCTS_SUCCESS',
  GET_PRODUCTS_FAILED: 'GET_PRODUCTS_FAILED',
  DELETE_PRODUCT_REQUESTED: 'DELETE_PRODUCT_REQUESTED',
  DELETE_PRODUCT_SUCCESS: 'DELETE_PRODUCT_SUCCESS',
  DELETE_PRODUCT_FAILED: 'DELETE_PRODUCT_FAILED',
  UPDATE_PRODUCT_REQUESTED: 'UPDATE_PRODUCT_REQUESTED',
  UPDATE_PRODUCT_SUCCESS: 'UPDATE_PRODUCT_SUCCESS',
  UPDATE_PRODUCT_FAILED: 'UPDATE_PRODUCT_FAILED',
};
